%YAML:1.0

dataset: "realsense"  # scannet, fusion_portable, realsense

# camera parameters 
image_width: 640
image_height: 480
camera_fx: 525.0
camera_fy: 525.0
camera_cx: 319.5
camera_cy: 239.5
depth_scale: 1000.0
depth_max: 4.0

# volumetric 
voxel_length: 0.02
sdf_trunc: 0.04
min_instance_points: 100 # for initial new instance

# associations
min_det_masks: 30 # pixel-wise
max_box_area_ratio: 0.9 # box_area/image_area
min_instance_masks: 20 # pixel-wise
dilate_kernal: 3 
min_iou: 0.3

# output
save_da_images: 1
tmp_dir: "/media/lch/SeagateExp/bag/sgslam/output"
