%YAML:1.0

dataset: "scannet"  # scannet, fusion_portable, realsense

# camera parameters 
image_width: 640
image_height: 480
camera_fx: 557.59
camera_fy: 578.73
camera_cx: 318.91
camera_cy: 242.68
depth_scale: 1000.0
depth_max: 4.0

# volumetric 
voxel_length: 0.02
sdf_trunc: 0.04
min_active_points: 200 # active instances
shape_min_points: 500 # export and bbox extract

# associations
min_det_masks: 100 # pixel-wise
max_box_area_ratio: 0.9 # box_area/image_area
dilate_kernal: 3 
min_iou: 0.3

# shape
min_voxel_weight: 0.1 # weight/observation_count

# merge over-segmentation
merge_inflation: 3.5
merge_iou: 0.4

# output
save_da_images: 0 # 1 for save
tmp_dir: "/media/lch/SeagateExp/dataset_/ScanNet/output_new"
